import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { extractDocumentLinks, rewriteDocumentLinks } from './links.js';
import { normalizeMarkdown, sha256, slugify, stableJson } from './model.js';

const MANAGED_START = '<!-- shiori:start -->';
const MANAGED_END = '<!-- shiori:end -->';

export async function compile(source, config) {
  const outputRoot = safeRepositoryPath(config.repositoryRoot, config.outputDirectory);
  const documents = await collectDocuments(source, config);
  const pathById = assignPaths(documents, config.rootDocumentId);
  const written = [];

  await rm(outputRoot, { recursive: true, force: true });
  await mkdir(outputRoot, { recursive: true });

  for (const document of documents.values()) {
    const target = pathById.get(document.id);
    const body = rewriteDocumentLinks(document.markdown, config, target, pathById);
    const content = frontmatter(document) + normalizeMarkdown(body);
    await write(outputRoot, target, content);
    written.push({ document, path: target, content });
  }

  const readme = `---\nlayout: default\ntitle: Archive index\n---\n\n${renderIndex(documents, pathById, config.rootDocumentId)}`;
  await write(outputRoot, 'README.md', readme);

  const manifest = createManifest(written, config);
  await write(outputRoot, 'manifest.json', stableJson(manifest));

  if (config.agentFile) await updateAgentFile(config);
  if (config.pages) {
    await write(dirname(outputRoot), '_data/shiori-nav.yml', renderNavigation(documents, pathById, config.rootDocumentId));
    await writePagesShell(config, outputRoot);
  }
  return { documentCount: documents.size, outputRoot, manifest };
}

export async function collectDocuments(source, config) {
  const found = new Map();
  const queue = [{ id: config.rootDocumentId, parentId: null, depth: 0 }];
  while (queue.length) {
    const item = queue.shift();
    if (found.has(item.id)) continue;
    if (found.size >= config.maxDocuments) throw new Error(`Export exceeded max-documents (${config.maxDocuments}). Narrow the root or raise the explicit cap.`);
    const document = await source.getDocument(item.id);
    if (!document || document.id !== item.id) throw new Error(`Source returned an invalid document for ${item.id}.`);
    const links = extractDocumentLinks(document.markdown, config).filter(id => id !== item.id);
    found.set(item.id, { ...document, parentId: item.parentId, depth: item.depth, childIds: links });
    for (const id of links) if (!found.has(id) && !queue.some(entry => entry.id === id)) queue.push({ id, parentId: item.id, depth: item.depth + 1 });
  }
  return found;
}

export function assignPaths(documents, rootId) {
  const paths = new Map([[rootId, 'overview.md']]);
  const used = new Set(['overview.md']);
  const queue = [rootId];
  while (queue.length) {
    const parentId = queue.shift();
    const parent = documents.get(parentId);
    for (const childId of parent.childIds) {
      if (!documents.has(childId) || paths.has(childId)) continue;
      const child = documents.get(childId);
      const parentPath = paths.get(parentId);
      const baseDir = parentId === rootId ? '' : parentPath.replace(/\.md$/, '');
      const base = slugify(child.title);
      let candidate = [baseDir, `${base}.md`].filter(Boolean).join('/');
      if (used.has(candidate)) candidate = [baseDir, `${base}--${slugify(childId).slice(0, 8)}.md`].filter(Boolean).join('/');
      paths.set(childId, candidate);
      used.add(candidate);
      queue.push(childId);
    }
  }
  return paths;
}

function createManifest(written, config) {
  return {
    schemaVersion: 1,
    generator: 'shiori',
    source: {
      type: 'affine',
      baseUrl: new URL(config.baseUrl).origin,
      workspaceId: config.workspaceId,
      rootDocumentId: config.rootDocumentId,
      traversal: 'same-workspace-links'
    },
    documents: written.sort((a, b) => a.path.localeCompare(b.path)).map(({ document, path, content }) => ({
      id: document.id,
      path,
      title: document.title,
      revision: document.revision,
      updatedAt: document.updatedAt,
      sha256: sha256(content)
    }))
  };
}

function renderIndex(documents, paths, rootId) {
  const lines = ['# Project knowledge archive', '', '> Generated by Shiori. AFFiNE is canonical; do not edit these files by hand.', '', `Start with [${escapeMd(documents.get(rootId).title)}](${paths.get(rootId)}).`, '', '## Contents', ''];
  const visit = (id, depth) => {
    const doc = documents.get(id);
    lines.push(`${'  '.repeat(depth)}- [${escapeMd(doc.title)}](${paths.get(id)})`);
    for (const childId of doc.childIds) if (documents.has(childId) && documents.get(childId).parentId === id) visit(childId, depth + 1);
  };
  visit(rootId, 0);
  return lines.join('\n') + '\n';
}

function renderNavigation(documents, paths, rootId) {
  const lines = [];
  const visit = (id, depth) => {
    const indent = '  '.repeat(depth);
    const children = documents.get(id).childIds.filter(childId => documents.has(childId) && documents.get(childId).parentId === id);
    lines.push(`${indent}- title: ${JSON.stringify(documents.get(id).title)}`, `${indent}  url: /brain/${paths.get(id).replace(/\.md$/, '.html')}`);
    if (children.length) {
      lines.push(`${indent}  children:`);
      for (const childId of children) visit(childId, depth + 2);
    }
  };
  visit(rootId, 0);
  return lines.join('\n') + '\n';
}

function frontmatter(document) {
  return `---\nlayout: default\ntitle: ${JSON.stringify(document.title)}\nshiori_source_id: ${JSON.stringify(document.id)}\n---\n\n`;
}

async function updateAgentFile(config) {
  const target = safeRepositoryPath(config.repositoryRoot, config.agentFile);
  let existing = '';
  try { existing = await readFile(target, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
  const block = `${MANAGED_START}\n## Project knowledge\n\nProject knowledge is available under \`${config.outputDirectory.replaceAll('\\', '/')}\`.\n\nRead \`${config.outputDirectory.replaceAll('\\', '/')}/README.md\` before planning substantial changes, then follow links to the relevant documentation. AFFiNE is canonical; these files are a generated snapshot and must not be edited manually.\n${MANAGED_END}`;
  const pattern = new RegExp(`${escapeRegExp(MANAGED_START)}[\\s\\S]*?${escapeRegExp(MANAGED_END)}`);
  const content = pattern.test(existing) ? existing.replace(pattern, block) : `${existing.trim()}${existing.trim() ? '\n\n' : ''}${block}\n`;
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, content, 'utf8');
}

async function writePagesShell(config, outputRoot) {
  const docsRoot = dirname(outputRoot);
  const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const templates = join(projectRoot, 'site');
  for (const [source, target] of [
    ['_config.yml', '_config.yml'],
    ['index.md', 'index.md'],
    ['_layouts/default.html', '_layouts/default.html'],
    ['_includes/nav.html', '_includes/nav.html'],
    ['assets/css/shiori.css', 'assets/css/shiori.css']
  ]) {
    const content = await readFile(join(templates, source), 'utf8');
    await write(docsRoot, target, content);
  }
}

function safeRepositoryPath(repositoryRoot, requested) {
  if (!requested || isAbsolute(requested)) throw new Error('Output paths must be non-empty and repository-relative.');
  const root = resolve(repositoryRoot);
  const target = resolve(root, requested);
  const rel = relative(root, target);
  if (!rel || rel === '..' || rel.startsWith(`..${sep}`)) throw new Error(`Path escapes the repository: ${requested}`);
  return target;
}

async function write(root, relativePath, content) {
  const target = resolve(root, relativePath);
  const rel = relative(resolve(root), target);
  if (rel === '..' || rel.startsWith(`..${sep}`)) throw new Error(`Generated path escaped output root: ${relativePath}`);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, content, 'utf8');
}

function escapeMd(value) { return value.replace(/[\[\]]/g, '\\$&'); }
function escapeRegExp(value) { return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
