import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, relative, resolve, sep } from 'node:path';
import { fetchSkillIcon } from './icons.js';
import { normalizeMarkdown, slugify, stableJson } from './model.js';

const STATE_FILE = '.shiori/generated-skills.json';
const GENERATED_PLUGIN_PREFIX = 'shiori-';

export async function generateSkills(documents, taggedIds, config) {
  const tagged = [...taggedIds]
    .filter(id => documents.has(id))
    .map(id => documents.get(id))
    .sort((a, b) => a.title.localeCompare(b.title) || a.id.localeCompare(b.id));

  const skills = assignSkillNames(tagged);
  await removePreviousGeneratedFiles(config.repositoryRoot);
  const generatedFiles = [];

  for (const skill of skills) {
    const iconUrl = skill.document.properties?.[config.skillIconProperty] ?? null;
    const icon = await fetchSkillIcon(iconUrl, config);
    const skillMd = renderSkill(skill);
    const reference = renderReference(skill.document);
    for (const root of projectSkillRoots(config)) {
      await writeGenerated(config.repositoryRoot, `${root}/${skill.name}/SKILL.md`, skillMd, generatedFiles);
      await writeGenerated(config.repositoryRoot, `${root}/${skill.name}/references/source.md`, reference, generatedFiles);
    }

    const pluginRoot = `${config.pluginDirectory}/${skill.pluginName}`;
    if (icon) {
      const relativePath = `assets/icon.${icon.extension}`;
      const repositoryPath = `${pluginRoot}/${relativePath}`;
      skill.icon = {
        relativePath,
        repositoryPath,
        publicUrl: config.repository ? rawGitHubUrl(config.repository, repositoryPath) : undefined
      };
      await writeGeneratedBuffer(config.repositoryRoot, repositoryPath, icon.bytes, generatedFiles);
    }
    await writeGenerated(config.repositoryRoot, `${pluginRoot}/skills/${skill.name}/SKILL.md`, skillMd, generatedFiles);
    await writeGenerated(config.repositoryRoot, `${pluginRoot}/skills/${skill.name}/references/source.md`, reference, generatedFiles);
    await writeGenerated(config.repositoryRoot, `${pluginRoot}/.claude-plugin/plugin.json`, stableJson(pluginManifest(skill, config)), generatedFiles);
    await writeGenerated(config.repositoryRoot, `${pluginRoot}/.cursor-plugin/plugin.json`, stableJson(cursorPluginManifest(skill, config)), generatedFiles);
    await writeGenerated(config.repositoryRoot, `${pluginRoot}/.zcode-plugin/plugin.json`, stableJson(zcodePluginManifest(skill, config)), generatedFiles);
    await writeGenerated(config.repositoryRoot, `${pluginRoot}/.devin-plugin/plugin.json`, stableJson(devinPluginManifest(skill, config)), generatedFiles);
  }

  await updateClaudeMarketplace(skills, config);
  await updateCursorMarketplace(skills, config);
  await updateZcodeMarketplace(skills, config);
  await updateDevinMarketplace(skills, config);
  await writeGenerated(config.repositoryRoot, STATE_FILE, stableJson({ schemaVersion: 2, tag: config.skillTag, iconProperty: config.skillIconProperty || null, files: generatedFiles.sort() }), []);
  return { count: skills.length, skills };
}

function assignSkillNames(documents) {
  const used = new Set();
  return documents.map(document => {
    const base = slugify(document.title).slice(0, 56).replace(/-+$/g, '') || 'untitled';
    let name = base;
    if (used.has(name)) name = `${base.slice(0, 47).replace(/-+$/g, '')}-${slugify(document.id).slice(0, 8)}`;
    used.add(name);
    return { name, pluginName: `${GENERATED_PLUGIN_PREFIX}${name}`, document };
  });
}

function projectSkillRoots(config) {
  return [...new Set([
    config.skillsDirectory,
    '.claude/skills',
    '.cursor/skills',
    '.windsurf/skills',
    '.vibe/skills',
    '.devin/skills'
  ].map(path => path.replaceAll('\\', '/').replace(/^\.\//, '').replace(/\/$/, '')))];
}

function renderSkill({ name, document }) {
  const description = `Use when a task involves ${document.title} or needs the corresponding AFFiNE-sourced project workflow and constraints.`;
  return `---\nname: ${name}\ndescription: ${JSON.stringify(description)}\n---\n\n# ${document.title}\n\n## When to use\n\nUse this skill when the task touches **${document.title}** or when its project-specific decisions and workflow are relevant.\n\n## Instructions\n\n1. Read [the generated AFFiNE reference](references/source.md) before planning or changing code.\n2. Apply the requirements, invariants, decisions, and workflow from that reference that are relevant to the task.\n3. If current repository behavior or explicit user direction conflicts with the reference, surface the conflict instead of silently choosing one.\n4. AFFiNE is canonical. Do not edit this generated skill or its reference by hand.\n`;
}

function renderReference(document) {
  return `# ${document.title}\n\n> Generated by Shiori from AFFiNE document \`${document.id}\`. AFFiNE is canonical.\n\n${normalizeMarkdown(document.markdown)}`;
}

function pluginManifest(skill, config) {
  return {
    name: skill.pluginName,
    version: '1.0.0',
    description: `AFFiNE-sourced Agent Skill for ${skill.document.title}.`,
    author: { name: 'Shiori' },
    repository: config.repository ? `https://github.com/${config.repository}` : undefined
  };
}

function cursorPluginManifest(skill, config) {
  return {
    name: skill.pluginName,
    displayName: `Shiori: ${skill.document.title}`,
    version: '1.0.0',
    description: `AFFiNE-sourced Agent Skill for ${skill.document.title}.`,
    author: { name: 'Shiori' },
    license: 'MIT',
    keywords: ['shiori', 'affine', 'project-knowledge'],
    logo: skill.icon?.relativePath
  };
}

function zcodePluginManifest(skill, config) {
  return {
    ...pluginManifest(skill, config),
    license: 'MIT',
    keywords: ['shiori', 'affine', 'project-knowledge'],
    skills: 'skills'
  };
}

function devinPluginManifest(skill, config) {
  return {
    ...pluginManifest(skill, config),
    license: 'MIT',
    keywords: ['shiori', 'affine', 'project-knowledge']
  };
}

async function updateClaudeMarketplace(skills, config) {
  const path = '.claude-plugin/marketplace.json';
  const existing = await readJson(config.repositoryRoot, path, {});
  const plugins = Array.isArray(existing.plugins) ? existing.plugins.filter(item => !isGeneratedPluginSource(item?.source, config)) : [];
  plugins.push(...skills.map(skill => marketplaceEntry(skill, config)));
  const value = {
    ...existing,
    $schema: existing.$schema ?? 'https://anthropic.com/claude-code/marketplace.schema.json',
    name: existing.name ?? config.marketplaceName,
    description: existing.description ?? 'AFFiNE-sourced project skills generated by Shiori.',
    owner: existing.owner ?? { name: config.repository?.split('/')[0] || 'Shiori' },
    plugins
  };
  await writeDirect(config.repositoryRoot, path, stableJson(value));
}

async function updateCursorMarketplace(skills, config) {
  const path = '.cursor-plugin/marketplace.json';
  const existing = await readJson(config.repositoryRoot, path, {});
  const plugins = Array.isArray(existing.plugins) ? existing.plugins.filter(item => !isGeneratedPluginSource(item?.source, config)) : [];
  plugins.push(...skills.map(skill => ({ name: skill.pluginName, source: `./${config.pluginDirectory}/${skill.pluginName}`, description: `AFFiNE-sourced Agent Skill for ${skill.document.title}.` })));
  const value = {
    ...existing,
    name: existing.name ?? config.marketplaceName,
    owner: existing.owner ?? { name: config.repository?.split('/')[0] || 'Shiori' },
    metadata: existing.metadata ?? { description: 'AFFiNE-sourced project skills generated by Shiori.', version: '1.0.0' },
    plugins
  };
  await writeDirect(config.repositoryRoot, path, stableJson(value));
}

async function updateZcodeMarketplace(skills, config) {
  const path = 'marketplace.json';
  const existing = await readJson(config.repositoryRoot, path, {});
  const plugins = Array.isArray(existing.plugins) ? existing.plugins.filter(item => !isGeneratedPluginSource(item?.source, config)) : [];
  plugins.push(...skills.map(skill => ({
    name: skill.pluginName,
    source: `./${config.pluginDirectory}/${skill.pluginName}`,
    description: `AFFiNE-sourced Agent Skill for ${skill.document.title}.`,
    version: '1.0.0',
    category: 'productivity',
    tags: ['shiori', 'affine', 'skill'],
    icon: skill.icon?.publicUrl
  })));
  const value = {
    ...existing,
    name: existing.name ?? config.marketplaceName,
    description: existing.description ?? 'AFFiNE-sourced project skills generated by Shiori.',
    plugins
  };
  await writeDirect(config.repositoryRoot, path, stableJson(value));
}

async function updateDevinMarketplace(skills, config) {
  const path = '.devin-plugin/plugin.json';
  const existing = await readJson(config.repositoryRoot, path, {});
  const requiredPlugins = Array.isArray(existing.requiredPlugins)
    ? existing.requiredPlugins.filter(item => !String(item?.path ?? '').startsWith(`${config.pluginDirectory}/${GENERATED_PLUGIN_PREFIX}`))
    : [];
  if (config.repository) {
    requiredPlugins.push(...skills.map(skill => ({
      source: 'git-subdir',
      url: `https://github.com/${config.repository}`,
      path: `${config.pluginDirectory}/${skill.pluginName}`
    })));
  }
  const value = {
    ...existing,
    name: existing.name ?? config.marketplaceName,
    version: existing.version ?? '1.0.0',
    description: existing.description ?? 'Meta-plugin for AFFiNE-sourced project skills generated by Shiori.',
    author: existing.author ?? { name: config.repository?.split('/')[0] || 'Shiori' },
    requiredPlugins
  };
  await writeDirect(config.repositoryRoot, path, stableJson(value));
}

function marketplaceEntry(skill, config) {
  return {
    name: skill.pluginName,
    description: `AFFiNE-sourced Agent Skill for ${skill.document.title}.`,
    author: { name: 'Shiori' },
    source: `./${config.pluginDirectory}/${skill.pluginName}`,
    category: 'productivity',
    version: '1.0.0'
  };
}

function isGeneratedPluginSource(source, config) {
  if (typeof source === 'string') return source.startsWith(`./${config.pluginDirectory}/${GENERATED_PLUGIN_PREFIX}`);
  return String(source?.path ?? '').startsWith(`${config.pluginDirectory}/${GENERATED_PLUGIN_PREFIX}`);
}

function rawGitHubUrl(repository, path) {
  const encodedPath = path.split('/').map(encodeURIComponent).join('/');
  return `https://raw.githubusercontent.com/${repository}/HEAD/${encodedPath}`;
}

async function removePreviousGeneratedFiles(repositoryRoot) {
  const state = await readJson(repositoryRoot, STATE_FILE, { files: [] });
  if (!Array.isArray(state.files)) return;
  for (const file of state.files) {
    if (typeof file !== 'string') continue;
    const target = safeRepositoryPath(repositoryRoot, file);
    await rm(target, { force: true });
  }
}

async function readJson(repositoryRoot, path, fallback) {
  try {
    return JSON.parse(await readFile(safeRepositoryPath(repositoryRoot, path), 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') return fallback;
    throw new Error(`Unable to read ${path}: ${error.message}`);
  }
}

async function writeGenerated(repositoryRoot, path, content, list) {
  await writeDirect(repositoryRoot, path, content);
  list.push(path.replaceAll('\\', '/'));
}

async function writeGeneratedBuffer(repositoryRoot, path, content, list) {
  const target = safeRepositoryPath(repositoryRoot, path);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, content);
  list.push(path.replaceAll('\\', '/'));
}

async function writeDirect(repositoryRoot, path, content) {
  const target = safeRepositoryPath(repositoryRoot, path);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, content, 'utf8');
}

function safeRepositoryPath(repositoryRoot, requested) {
  if (!requested || isAbsolute(requested)) throw new Error('Generated skill paths must be non-empty and repository-relative.');
  const root = resolve(repositoryRoot);
  const target = resolve(root, requested);
  const rel = relative(root, target);
  if (!rel || rel === '..' || rel.startsWith(`..${sep}`)) throw new Error(`Generated skill path escapes the repository: ${requested}`);
  return target;
}
